AllCops:
  TargetRubyVersion: 2.3
# Remove top-level class documentation requirement
Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
#ignore double quote error
Style/StringLiterals:
  Enabled: false
